name: Getting Started

on: push

jobs:
  # This workflow contains a single job called "build"
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/Checkout@v2
        
      - name: Checkout code
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB.TOKEN}}

